name: quizzler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rflutter_alert: ^2.0.2
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  

flutter:
  uses-material-design: true
  fonts:
  - family: MonteCarlo
    fonts:
    - asset: fonts/MonteCarlo-Regular.ttf
  - family: Sacramento
    fonts:
    - asset: fonts/Sacramento-Regular.ttf
  - family: Lobster
    fonts:
    - asset: fonts/Lobster-Regular.ttf

